# Generated by Django 3.1.2 on 2020-12-08 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressline1', models.CharField(max_length=50)),
                ('addressline2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpages.address')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gpaceiling', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birthdate', models.DateTimeField()),
                ('username', models.CharField(max_length=50)),
                ('interests', models.ManyToManyField(null=True, to='mainpages.JobCategory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpages.address')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainpages.person')),
                ('role', models.CharField(max_length=50)),
            ],
            bases=('mainpages.person',),
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainpages.person')),
                ('recievenewsletter', models.BooleanField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpages.applicant')),
                ('skills', models.ManyToManyField(to='mainpages.Skill')),
            ],
            bases=('mainpages.person',),
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wagetype', models.CharField(max_length=50)),
                ('gpareq', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ispublic', models.BooleanField()),
                ('relocationassist', models.BooleanField()),
                ('appopendate', models.DateTimeField()),
                ('appclosingdate', models.DateTimeField()),
                ('decisiondate', models.DateTimeField()),
                ('jobstartdate', models.DateTimeField()),
                ('category', models.ManyToManyField(to='mainpages.JobCategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpages.company')),
                ('requiredskills', models.ManyToManyField(to='mainpages.Skill')),
                ('zipcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpages.zip')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacttype', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=30)),
                ('ispublic', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpages.person')),
            ],
        ),
        migrations.CreateModel(
            name='AutoApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wagerequirement', models.DecimalField(decimal_places=2, max_digits=8)),
                ('needsrelocatassist', models.IntegerField()),
                ('category', models.ManyToManyField(to='mainpages.JobCategory')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpages.resume')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpages.applicant')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpages.zip'),
        ),
        migrations.AddField(
            model_name='resume',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpages.applicant'),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100000)),
                ('sentdate', models.DateTimeField()),
                ('sentto', models.ManyToManyField(related_name='sentto', to='mainpages.Person')),
                ('sentby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sentby', to='mainpages.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainpages.person')),
                ('position', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpages.company')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpages.employer')),
            ],
            bases=('mainpages.person',),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitdate', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('autoapply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainpages.autoapply')),
                ('jobposting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpages.jobposting')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpages.resume')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpages.applicant')),
            ],
        ),
    ]
