# Generated by Django 3.1.2 on 2020-12-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default='user', max_length=50),
            preserve_default=False,
        ),
    ]
