# Generated by Django 3.1.2 on 2020-12-08 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0004_auto_20201207_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jobposting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpages.jobposting'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpages.company'),
        ),
    ]
