# Generated by Django 3.1.2 on 2020-12-08 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='autoapply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainpages.autoapply'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
