# Generated by Django 3.1.2 on 2020-12-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0008_resume_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='interests',
            field=models.ManyToManyField(null=True, to='mainpages.JobCategory'),
        ),
    ]
