# Generated by Django 3.1.2 on 2020-12-08 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0009_person_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpages.applicant'),
        ),
    ]
